In [1]:
# Imports
import numpy as np

In [ ]:
# Receiving user input

name = input("Digite seu nome: ")

In [2]:
print("Olá " + name + ", feliz em dizer: hello world!")

Olá leo, feliz em dizer: hello world!


In [ ]:
# Dictionaries

dict = {"nome":"leo", "idade":-5, "cidade":"delhi"}

In [10]:
dict["nome"]

'leo'

In [ ]:
# To print all dictionary values

for key, value in dict.items():
    print(key, value)

nome leo
idade -5
cidade delhi


In [ ]:
# lists
list = [1,2,3,4]
list

[1, 2, 3, 4]

#### numpy

In [ ]:
# ndarray -> n-dimensional array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a.dtype

dtype('int64')

In [ ]:
# Dimensão do array
print(a.ndim)
# Size of array with 3 values
print(a.size)
# The format of the array, showing that it has only three values ​​in "row" and no values ​​in "column"
print(a.shape)

1
3
(3,)


In [ ]:
# Creating a matrix
b = np.array([[1.3, 2.4],[0.3, 4.1]])
print(b.dtype)
print(b.ndim)
print(b.size)
print(b.shape)

float64
2
4
(2, 2)


In [ ]:
# Size in bytes
print(b.itemsize) 
# Location in the memory
print(b.data)

8


In [37]:
# The array() function, in addition to lists, can accept tuples and sequences of tuples.
c = np.array(((1,2,3),(4,5,6)))
# It can also accept sequences of tuples and interconnected lists.
d = np.array([(1,2,3),[4,5,6],(7,8,9)])

print(c,'\n')
print(d)

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# remembering we can use string type too.
# all supported types are in Python Data Analytics With Pandas, Numpy, and Matplotlib.docx.
e = np.array([['a','b'],['c','d']])
e

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [2]:
# For set a type to your list or tuples
f = np.array( [ [1,2,3],[4,5,6] ], dtype=complex )
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [ ]:
# The zeros() function, for example, creates a full array of zeros with dimensions
# defined by the shape argument. For example, to create a two-dimensional array 3x3,
# you can use:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# While the ones() function:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# arange() function generates NumPy arrays
# with numerical sequences that respond to particular rules depending on the passed
# arguments:
print(np.arange(0,10))
print(np.arange(4,10), '\n')
print(np.arange(0,11))
print(np.arange(4,11))

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9] 

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]


In [ ]:
# It is also possible to generate a sequence of values with precise intervals between them
# adding the third argument:
np.arange(0,11,2)
# In addition, this third argument can also be a float.

array([ 0,  2,  4,  6,  8, 10])

In [16]:
# reshape() function divides a linear array in different parts in the manner
# specified by the shape argument:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Remembering that to cut the array, the values ​​must be divisible by the size of the array
# or you will get a error: "cannot reshape array of size 11 into shape (3,4)"
np.arange(0,11).reshape(3,4)

In [19]:
# linspace() function the third argument defines the
# number of elements into which we want the interval to be split.
np.linspace(0,11,5, dtype=int)

array([ 0,  2,  5,  8, 11])

In [35]:
# random functon:
print(np.random.random(3), '\n')
print(np.random.random((3,3)))

[0.86627533 0.34843748 0.65692947] 

[[0.72990689 0.87374301 0.90667513]
 [0.9140526  0.31783006 0.40313131]
 [0.60395049 0.52680533 0.22082555]]


### Basic Operations

In [38]:
# arithmetic operators
a = np.arange(1,5)
print(a, '\n')
print('Add: ', a + 4)
print('Sub: ', a - 4)
print('Multi: ', a * 4)
print('Div: ', a / 4)

[1 2 3 4] 

Add:  [5 6 7 8]
Sub:  [-3 -2 -1  0]
Multi:  [ 4  8 12 16]
Div:  [0.25 0.5  0.75 1.  ]


In [1]:
# These operators can also be used between two arrays. In NumPy, these operations
# are element-wise, that is, the operators are applied only between corresponding
# elements. These are objects that occupy the same position, so that the end result will be
# a new array containing the results in the same location of the operands.
b = np.arange(5, 9)
print( b )
print('Add: ', a + b)
print('Sub: ', a - b)
print('Multi: ', a * b)
print('Div: ', a / b)


NameError: name 'np' is not defined

In [45]:
# these operators are also available for functions, provided that the value
# returned is a NumPy array
print(a * np.sin(b), '\n')
print(a * np.sqrt(b))

[-0.95892427 -0.558831    1.9709598   3.95743299] 

[ 2.23606798  4.89897949  7.93725393 11.3137085 ]


In [ ]:
# Moving on to the multidimensional case, even here the arithmetic operators
# continue to operate element-wise
